//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickmeJaeger
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public int DishId { get; set; }
        public string DishName { get; set; }
        public Nullable<decimal> DishPrice { get; set; }
        public Nullable<int> DishWeight { get; set; }
        public string DishDescription { get; set; }
        public string DishType { get; set; }
        public string DishImage { get; set; }
    }
}
