//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickmeJaeger
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEWS
    {
        public int ReviewID { get; set; }
        public Nullable<int> UserRID { get; set; }
        public string ReviewText { get; set; }
        public string ReviewImage { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
